[package]
name = "clg"
version = "0.1.0"
authors = ["Mario Zupan <mario@zupzup.org>"]
edition = "2018"

[dependencies]
hyper = "0.12.27"
hyper-tls = "0.3.2"
failure = "0.1.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.1.13"
toml = "0.5"
clap = "2.33.0"
git2 = "0.8.0"


